module.exports = {
    MISSING_FIELDS: 101,
    INVALID_PAYMENT_TYPE: 301,
    INVALID_CARD_DIGITS: 302,
    INVALID_CARD_LENGTH: 303,
    INVALID_CARD_EXPIRATION: 304,
    INVALID_CARD_CVV: 305,
    INVALID_BALANCE_TYPE: 201,
    INVALID_ORDER_AMOUNT: 202,
}